# for postgresql connection
POSTGRES_CONFIG = { # 보안상 문제로 이렇게 하면 안되긴 하는데 그건 담에
    "C2C_USER": "edw2n",
    "C2C_PASSWORD": "p4dsc2c",
    "C2C_HOST": "localhost",
    "C2C_PORT": "5432",
    "C2C_DB": "c2c"
}

SCHEMA_NAME = "public"
TABLE_NAME = ["GroundTruth", "ProductInfo", "QC", "User", "DatasetInfo", "Features", "Transaction", "Object"]
ALL_COLUMNS = [[   
                    'gt_id', 'img_id', 'gt_object_id',
                    'gt_height','gt_width','gt_length',
                    'gt_Xordinate', 'gt_Yordinate', 'gt_Zordinate',
                    'gt_Xrotate', 'gt_Yrotate', 'gt_Zrotate', 'gt_state', 
                    'gt_occlusion', 'gt_occlusion_kf','gt_truncation',
                    'gt_amt_occlusion', 'gt_amt_occlusion_kf', 'gt_amt_border_l', 'gt_amt_border_r', 'gt_amt_border_kf'
                ],
                [
                    'product_id', 'price', 'sold_count' 
                ],
                [
                    'qc_id', 'qc_status', 'qc_start_date', 'qc_end_date', 'qc_score', 'object_type', 'object_count', 'tag'
                ],
                [
                    'user_id', 'user_idName', 'user_password' 
                ],
                [
                    'dataset_id', 'dataset_name', 'dataset_description'
                ],
                [
                    'img_id','lat', 'lon', 'alt', 'roll', 'pitch', 'yaw',
                    'velo_north', 'velo_east', 'velo_forward', 'velo_leftward', 'velo_upward',
                    'accel_x', 'accel_y', 'accel_z', 'accel_forward', 'accel_leftward', 'accel_upward',
                    'ang_x', 'ang_y', 'ang_z', 'ang_forward', 'ang_leftward', 'ang_upward',
                    'pos_accuracy', 'vel_accuracy',
                    'navstat', 'numsats', 'posmode', 'velmode', 'orimode',
                    'qc_id', 'user_id', 'product_id', 'dataset_id', 
                    'image_path', 'image_width', 'image_height',
                    'upload_date', 'contrast', 'brightness', 'sharpness', 'saturation', 'like_cnt'
                ],
                [
                    'tx_id', 'tx_date', 'img_id', 'buyer_id', 'seller_id'
                ],
                [
                    'gt_object_id', 'gt_object'
                ]
            ]
PK_LIST = ['gt_id', 'product_id', 'qc_id', 'user_id', 'dataset_id','img_id','tx_id', 'gt_object_id']
## PK table, PK column, FK table, FK column
FK_LIST = [('Features','img_id', 'GroundTruth', 'img_id'),
           ('Object', 'gt_object_id', 'GroundTruth', 'gt_object_id'),
           ('ProductInfo', 'product_id', 'Features', 'product_id'),
           ('QC', 'qc_id', 'Features', 'qc_id',),
           ('User', 'user_id', 'Features', 'user_id'),
           ('DatasetInfo', 'dataset_id','Features', 'dataset_id'),
           ('Features', 'img_id', 'Transaction', 'img_id'),
           ('User', 'user_id', 'Transaction', 'buyer_id'),
           ('User', 'user_id', 'Transaction', 'seller_id')
           ]

# GroundTruth 
GROUNDTRUTH_COLUMNS_INFO = {
    "gt_id":               "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "img_id":              "bigint NULL",
    "gt_object_id":        "bigint NULL",
    "gt_height":           "numeric NULL",
    "gt_width":            "numeric NULL",
    "gt_length":           "numeric NULL",
    "gt_Xordinate":        "numeric NULL",
    "gt_Yordinate":        "numeric NULL",
    "gt_Zordinate":        "numeric NULL",
    "gt_Xrotate":          "numeric NULL",
    "gt_Yrotate":          "numeric NULL",
    "gt_Zrotate":          "numeric NULL",
    "gt_state":            "numeric NULL",
    "gt_occlusion":        "numeric NULL",
    "gt_occlusion_kf":     "numeric NULL",
    "gt_truncation":       "numeric NULL",
    "gt_amt_occlusion":    "numeric NULL",
    "gt_amt_occlusion_kf": "numeric NULL",
    "gt_amt_border_l":     "numeric NULL",
    "gt_amt_border_r":     "numeric NULL",
    "gt_amt_border_kf":    "numeric NULL"
}

# ProductInfo
PRODUCTINFO_COLUMNS_INFO = {
    "product_id": "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "price":      "bigint NULL",
    "sold_count": "bigint NULL"
}

# QC
QC_COLUMNS_INFO = {
    "qc_id":         "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "qc_status":     "varchar(50) NOT NULL",
    "qc_start_date": "timestamp NULL",
    "qc_end_date":   "timestamp NULL",
    "qc_score":      "numeric NULL",
    "object_type":   "varchar(50) NULL",
    "object_count":  "bigint NULL",
    "tag":           "varchar(50) NULL"
}

# User 
USER_COLUMNS_INFO = {
    "user_id":       "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "user_idName":   "varchar(50) NOT NULL",
    "user_password": "varchar(50) NOT NULL",
}

# DatasetInfo
DATASETINFO_COLUMNS_INFO = {
    "dataset_id":           "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "dataset_name":         "varchar(50) NULL",
    "dataset_description":  "varchar(512) NULL"
}

# Features
FEATURES_COLUMNS_INFO = {
    "img_id":         "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "image_path":     "varchar(256) NULL",
    "image_width":    "bigint NULL",
    "image_height":   "bigint NULL",
    "upload_date":    "timestamp NULL",
    "contrast":       "numeric NULL",
    "brightness":     "numeric NULL",
    "sharpness":      "numeric NULL",
    "saturation":     "numeric NULL",
    "lat":            "numeric NULL",
    "lon":            "numeric NULL",
    "alt":            "numeric NULL",
    "roll":           "numeric NULL",
    "pitch":          "numeric NULL",
    "yaw":            "numeric NULL",
    "velo_north":     "numeric NULL",
    "velo_east":      "numeric NULL",
    "velo_forward":   "numeric NULL",
    "velo_leftward":  "numeric NULL",
    "velo_upward":    "numeric NULL",
    "accel_x":        "numeric NULL",
    "accel_y":        "numeric NULL",
    "accel_z":        "numeric NULL",
    "accel_forward":  "numeric NULL",
    "accel_leftward": "numeric NULL",
    "accel_upward":   "numeric NULL",
    "ang_x":          "numeric NULL",
    "ang_y":          "numeric NULL",
    "ang_z":          "numeric NULL",
    "ang_forward":    "numeric NULL",
    "ang_leftward":   "numeric NULL",
    "ang_upward":     "numeric NULL",
    "like_cnt":       "bigint NULL",
    "pos_accuracy":   "numeric NULL",
    "vel_accuracy":   "numeric NULL",
    "navstat":        "bigint NULL",
    "numsats":        "bigint NULL",
    "posmode":        "bigint NULL",
    "velmode":        "bigint NULL",
    "orimode":        "bigint NULL",
    "qc_id":          "bigint NULL",
    "user_id":        "bigint NULL",
    "product_id":     "bigint NULL",
    "dataset_id":     "bigint NULL",
}

# transaction
TRANSACTION_COLUMNS_INFO = {
    "tx_id":     "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "tx_date":   "timestamp NOT NULL",
    "img_id":    "bigint NOT NULL",
    "buyer_id":  "bigint NOT NULL",
    "seller_id": "bigint NOT NULL",
}

OBJECT_COLUMNS_INFO = {
    "gt_object_id":     "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "gt_object":        "varchar(50) NULL"
}

ALL_COLUMNS_INFO = [GROUNDTRUTH_COLUMNS_INFO, PRODUCTINFO_COLUMNS_INFO, 
                    QC_COLUMNS_INFO,USER_COLUMNS_INFO, DATASETINFO_COLUMNS_INFO, 
                    FEATURES_COLUMNS_INFO, TRANSACTION_COLUMNS_INFO,
                    OBJECT_COLUMNS_INFO]
